### PR TITLE
TC added: FullLuceneShowcasetestSearchMaitreyapraṇidhana()

### PR DESCRIPTION
**Pull request by sten1ee**
@eroux, are you ok with this 'Maitreyapraṇidhana' TC ?
Is it ok, as it is now (passing) or it is supposed to fail at the present moment (i.e. have different score on some of the 8 tested docs) ?

### CODE REVIEW

**Comment by eroux** [comment]
the score computed by Lucene is not something that's really understandable by a human so I have really no clue what the scores should be (or even if it makes sense to have an opinion on the matter). What puzzles me is that the first two are equal but give different scores... I can't find a reasonable reason for that but I didn't look at the code closely... do you think there is a reason?

But in any case, I suspect the scores will vary with the version of Lucene so I'm not sure hardcoding them is a good idea... maybe you can sort by score order and check if the order is the one you expect?

**Comment by sten1ee** [comment]
I know that the scores are rather volatile and will most probably change across different versions of Lucene.
As a remedy I am checking for _approximate_ score (with epsilon set to +/-0.01)
Your idea about checking the order is not directly applicable, as some pairs (or even triples) of docs get exactly the same score hence those may be score-sorted in any permutation and spoil the expected order.
Regarding your question
```
What puzzles me is that the first two are equal but give different scores... I can't find a reasonable reason for that but I didn't look at the code closely... do you think there is a reason?
```
Yes, there is difference - a couple of soft hyphens in the second case (but github is not displaying those). The second doc looks like 'Maitreya-­praṇidhana­-rāja' in a proper editor.

So, any alternative ideas?
E.g. increase the epsilon value from 0.01 to 0.1 ?

**Comment by eroux** [comment]
ooooh ok thanks, that's reassuring!

For the epsilon yes, let's make it a bit higher

For the soft hyphens, they should only be used by the analyzer to cut the syllable but shouldn't be indexed... can you check if the analyzer produces tokens that includes the hyphens? If so, we need to find a way to remove them, it doesn't make sense that they change the score so much...

**Comment by eroux** [comment]
I've isolated the bug and turned into a (failing) test in https://github.com/buda-base/lucene-sa/commit/b8a5b9d5faad6defe1b9dc77493ae8154adf15cf 

I think it might be an unfortunate interaction between the lenient code and the syllable tokenizer but maybe it's more simple than that. It's not triggered when there's a soft hyphen between `na` and `ra`, which explains the difference of score.

Can you try to take a look?

**Comment by sten1ee** [comment]
I did some experiments aside from your TC and the results concur with your observation -
w/o soft hyphen between 'na' and 'ra' the tokenizer will give us 'nara'
Don't know if this was what you were asking for?

**Comment by eroux** [comment]
oh, I meant: can you try to fix it?

**Comment by sten1ee** [comment]
Ок :)
Where should I be looking for the problem?
SkrtSyllableTokenizer ?

**Comment by eroux** [comment]
that sounds like a reasonable start yes. Something to be aware of is that the `r` is generally a problem in lenient mode as it can be either a semi-vowel (`ṛ`) or a consonant (`r`), which the syllable tokenizer treats differently. There's no perfect solution for this, but we should just reajust (this will give other types of errors but hopefully they will be less commons)

**Pull request merged**
